
# Avoid use_frameworks! declaration in your Podfile. Contact us at support@webengage.com if you face any issue.

platform :ios, '9.0'

workspace '../WEGExtension'

target 'WEGExtensionApp' do
  pod 'WebEngage'
end


target 'ServiceExtension' do
  platform :ios, '10.0'
  pod 'WebEngageBannerPush', :path => '../'
  # pod 'WebEngageAppEx/NotificationService', :path => '../'
end

target 'ContentExtension' do
  platform :ios, '10.0'
  pod 'WebEngageAppEx/ContentExtension', :path => '../'
end
